### ISSUE TITLE
Plugin is not compatible with CopyWebpackPlugin

### ISSUE THREAD

**Issue by sebastien-savalle** [icelam/html-inline-script-webpack-plugin#114]
## Environment and package version

```
"devDependencies": {
    "babel-loader": "^8.2.2",
    "compression-webpack-plugin": "^7.1.2",
    "copy-webpack-plugin": "^8.1.1",
    "css-loader": "^5.2.4",
    "css-minimizer-webpack-plugin": "^2.0.0",
    "eslint": "^7.24.0",
    "html-inline-css-webpack-plugin": "^1.11.0",
    "html-inline-script-webpack-plugin": "^2.0.0",
    "html-webpack-plugin": "^5.3.1",
    "tslib": "^2.2.0",
    "webpack": "^5.35.0",
    "webpack-cli": "^4.6.0",
    "webpack-dev-server": "^3.11.2"
  }
```

## Reproduction link / code sample

Webpack.config.js
```
const path = require('path');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const CompressionPlugin = require('compression-webpack-plugin');
const HtmlInlineScriptPlugin = require('html-inline-script-webpack-plugin');
const CssMinimizerPlugin = require('css-minimizer-webpack-plugin');
const CopyPlugin = require('copy-webpack-plugin');

module.exports = {
    entry: './www/app/app.js',
    output: {
        path: path.resolve(__dirname, 'dist'),
        filename: 'bundle.min.js',
        clean: true
    },
    module: {
        rules: [
            {
                test: /\.js$/u,
                exclude: /node_modules/u,
                use: {
                    loader: "babel-loader"
                }
            },
            {
                test: /\.css$/u,
                use: ['css-loader']
            }
        ]
    },
    optimization: {
        minimize: true,
        minimizer: [
            `...`,
            new CssMinimizerPlugin(),
        ],
    },
    plugins: [
        new CopyPlugin({
            patterns: [
                { from: 'www/lib', to: 'gzip' }
            ],
        }),
        new HtmlWebpackPlugin({
            template: 'www/index.html'
        }),
        new HtmlInlineScriptPlugin(),
        new CompressionPlugin(),
    ],
    devServer: {
        port: 3000,
        contentBase: './dist'
    }
}
```

## Steps to reproduce

Create a project including both html-inline-script-webpack-plugin and copy-webpack-plugin and build it.

## What is expected?

The release should contains the html generated by webpack including the script inlined and the content of the www/lib folder copied to the dist/gzip folder.

## What is actually happening?

The html is correctly generated but libs are not copied to the dist/gzip folder. 
The libs are correctly copied when your plugin is not called.

Thanks,
Sebastien

**Comment by sebastien-savalle** [comment]
I found a workaround using the plugin configuration.
I restricted it to files ending in .js

> new HtmlInlineScriptPlugin([
>             /.+[.]js$/
>           ])

I think it should not be possible to inline gzip scripts by default.

**Comment by icelam** [comment]
Hi @sebastien-savalle, thank you for submitting this issue. 

I've totally missed out in a more complicated scenario, it is possible that some of the script not part of `entry` script. Agree on your point that the plugin should avoid processing those script (e.g. static assets copied via `copy-webpack-plugin`). 

I will consider this as an enhancement and see if it is possible to identify whether the script is part of `entry`.

Meanwhile, the recommended way of solving it would be adding a regex to exclude the `gzip` folder :
```
new HtmlInlineScriptPlugin([/^((?!gzip).).+[.]js$/])
```

**Comment by icelam** [comment]
This should be resolve in the latest version 2.0.3 (webpack 5) / 1.15 (webpack 4). Closing the issue now. If you think it is not resolving the issue, welcome to reopen it and let me know :)
