### ISSUE TITLE
npm v1.1.5 errors with "Version 2.x only supports webpack 5"

### ISSUE THREAD

**Issue by sean256** [icelam/html-inline-script-webpack-plugin#290]
## Environment and package version
webpack: v4.x
html-inline-script-webpack-plugin: v1.1.5

## Reproduction link / code sample

No need to actually run a build, just look at the code for index.js npm installs:

```
npm i html-inline-script-webpack-plugin@^1 -D
cat node_modules/html-inline-script-webpack-plugin/dist/index.js
```

Or download directly: https://registry.npmjs.org/html-inline-script-webpack-plugin/-/html-inline-script-webpack-plugin-1.1.5.tgz

## What is expected?
It should not claim to be version 2 and should not claim that webpack 5 is required

## What is actually happening?
It claims to be v2

**Comment by icelam** [comment]
@sean256 I have publish v1.1.6 to fix the broken version. Welcome to reopen the issue anytime if the issue still exists.

**Comment by qiwang97** [comment]
@icelam  I get the error `Please upgrade your webpack to version 4 to use this plugin.`

Here is my pkgs：
```
"webpack": "^4.44.1",
    "webpack-bundle-analyzer": "^3.3.2",
    "webpack-cli": "^3.3.12",
    "webpack-dev-server": "^3",
    "webpack-merge": "^4.1.2"

"html-inline-script-webpack-plugin": "^1", //  "version": "1.1.6" in package-lock.json
```
