### ISSUE TITLE
inline script only in head section? it's posible other locations?

### ISSUE THREAD

**Issue by oldlastman** [icelam/html-inline-script-webpack-plugin#352]
it's posible to indicate where i want my inline code? for example before /body ?
i try to use template options but i think it's no posible

## Environment and package version

    "html-inline-script-webpack-plugin": "^3.0.0",
    "html-webpack-plugin": "^5.5.0",
    "webpack": "^5.70.0",

## Reproduction link / code sample

plugins: [
      new HtmlWebpackPlugin({
        title: 'my title',
        filename: 'index.html',
        template: 'src/assets/main.html',
      }),
      new HtmlInlineScriptPlugin({
        htmlMatchPattern: [/index.html$/],
      }),
    ],

## Steps to reproduce

i just trying basic example

## What is expected?

i could indicate where i want my inline code

## What is actually happening?

only appears in head section, first line

thanks (sorry if this a silly question...)

**Comment by icelam** [comment]
Hi @oldlastman, this can be achieve by setting the `inject` options in `html-webpack-plugin` listed on their documentation: https://github.com/jantimon/html-webpack-plugin#options.

For example, if you wish to inject the scripts within `<body>`, you can do:
```diff
plugins: [
     new HtmlWebpackPlugin({
        title: 'my title',
        filename: 'index.html',
        template: 'src/assets/main.html',
+       inject: 'body',
    }),
    new HtmlInlineScriptPlugin({
        htmlMatchPattern: [/index.html$/],
    }),
],
```

**Comment by icelam** [comment]
A easier way to move script tags to body maybe without plugins or chunks optimisation could be:
https://github.com/jantimon/html-webpack-plugin/blob/main/examples/custom-insertion-position/readme.md

```
<%= htmlWebpackPlugin
      .tags
      .headTags
      .filter((tag) => tag.tagName === 'script')
      .join('')
%>
```

**Comment by mehimanshupatil** [comment]
as @icelam mentioned, I use `inject: 'body'`  to inject script at bottom of body. which don't require a template

` When passing 'body' to inject all javascript resources will be placed at the bottom of the body element.`

**Comment by oldlastman** [comment]
thanks for your help @mehimanshupatil & @icelam 
both method  works perfect
(I only learn how to use webpack and test mini ideas on weekends, sorry for this delay in my answer )

**Comment by icelam** [comment]
@oldlastman No worries, I am glad it helped 😄
